// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8mOJUbAF4YrHA2MxMOcW_uSLaxxPSkSU',
    appId: '1:775710742379:web:175898fca775a494601e2e',
    messagingSenderId: '775710742379',
    projectId: 'chat2023-8664a',
    authDomain: 'chat2023-8664a.firebaseapp.com',
    databaseURL: 'https://chat2023-8664a-default-rtdb.firebaseio.com',
    storageBucket: 'chat2023-8664a.appspot.com',
    measurementId: 'G-H67K9THXBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx9JNm_naxXvJitfTR8g9JqnUT47iizv4',
    appId: '1:775710742379:android:eac30e1d4500a45d601e2e',
    messagingSenderId: '775710742379',
    projectId: 'chat2023-8664a',
    databaseURL: 'https://chat2023-8664a-default-rtdb.firebaseio.com',
    storageBucket: 'chat2023-8664a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMcH52Ae12PiRMH4FT6u9MylOBX1DI9iI',
    appId: '1:775710742379:ios:1cce65748336b2a6601e2e',
    messagingSenderId: '775710742379',
    projectId: 'chat2023-8664a',
    databaseURL: 'https://chat2023-8664a-default-rtdb.firebaseio.com',
    storageBucket: 'chat2023-8664a.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMcH52Ae12PiRMH4FT6u9MylOBX1DI9iI',
    appId: '1:775710742379:ios:4cd27981ff179fcc601e2e',
    messagingSenderId: '775710742379',
    projectId: 'chat2023-8664a',
    databaseURL: 'https://chat2023-8664a-default-rtdb.firebaseio.com',
    storageBucket: 'chat2023-8664a.appspot.com',
    iosBundleId: 'com.example.gtkFlutter.RunnerTests',
  );
}
